export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

{
  /* 
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap" rel="stylesheet">
                
<link href="css/bootstrap.min.css" rel="stylesheet">
<link href="css/bootstrap-icons.css" rel="stylesheet">
<link href="css/templatemo-topic-listing.css" rel="stylesheet">      */
}
import '../public/css/bootstrap.min.css'
import '../public/css/bootstrap-icons.css'
import '../public/css/templatemo-topic-listing.css'

export default function RootLayout ({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <head>
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin=''
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Montserrat:wght@500;600;700&family=Open+Sans&display=swap'
          rel='stylesheet'
        />
        <script src='js/jquery.min.js' defer></script>
        <script src='js/bootstrap.bundle.min.js' defer></script>
        <script src='js/jquery.sticky.js' defer></script>
        <script src='js/click-scroll.js' defer></script>
        <script src='js/custom.js' defer></script>
      </head>
      <body id='top'>{children}</body>
    </html>
  )
}
